// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOF8_CjwXLWnaeqSmjqpquh-dY2NMLmI0',
    appId: '1:748822231626:web:ea00585b7258b0b9a684b3',
    messagingSenderId: '748822231626',
    projectId: 'rss-app-8670d',
    authDomain: 'rss-app-8670d.firebaseapp.com',
    storageBucket: 'rss-app-8670d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvp7EhEmVKHoWZOKPpm1vlXxkdxiS4kuI',
    appId: '1:748822231626:android:8b6de87161d6f380a684b3',
    messagingSenderId: '748822231626',
    projectId: 'rss-app-8670d',
    storageBucket: 'rss-app-8670d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpn3VLqSOgL1ehIPC6nqiJA3KmAj11sZg',
    appId: '1:748822231626:ios:a4235b9548bb303ea684b3',
    messagingSenderId: '748822231626',
    projectId: 'rss-app-8670d',
    storageBucket: 'rss-app-8670d.appspot.com',
    iosClientId: '748822231626-iok6d0oueo5fa8gjnrlc5am9cj38c432.apps.googleusercontent.com',
    iosBundleId: 'com.example.rrsOkuyucuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpn3VLqSOgL1ehIPC6nqiJA3KmAj11sZg',
    appId: '1:748822231626:ios:a4235b9548bb303ea684b3',
    messagingSenderId: '748822231626',
    projectId: 'rss-app-8670d',
    storageBucket: 'rss-app-8670d.appspot.com',
    iosClientId: '748822231626-iok6d0oueo5fa8gjnrlc5am9cj38c432.apps.googleusercontent.com',
    iosBundleId: 'com.example.rrsOkuyucuApp',
  );
}
